---
- include: common.yml

# This is a setup for vagrant host, inherits from all
- hosts: default
  sudo: yes
  roles:
    - { role: php, use_php56: true, use_xdebug: true }
    - { role: mysql, use_mysql56: true}
    - { role: composer, use_composer_no_dev: no }

  tasks:
    - name: Update bashrc for with the app environment
      lineinfile:
        dest=/home/vagrant/.bashrc
        line="export APPLICATION_ENVIRONMENT=dev"
        state=present
        insertafter=EOF
        create=True

  handlers:
    - include: roles/apache/handlers/main.yml
