---
- include: common.yml

# This is a setup for vagrant host, inherits from all
- hosts: default
  sudo: yes
  roles:
    - nodejs
    - { role: php, use_php56: true, use_xdebug: true }
    - { role: mysql, use_mysql56: true}
    - { role: composer, use_composer_no_dev: no, install_vendors: false }

  tasks:
    - name: restart Apache
      service: name=apache2 state=restarted
      sudo: yes
